// Code generated by Kitex v0.10.1. DO NOT EDIT.

package two

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	echo "multiple/kitex_gen/echo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Two": kitex.NewMethodInfo(
		twoHandler,
		newTwoArgs,
		newTwoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	twoServiceInfo                = NewServiceInfo()
	twoServiceInfoForClient       = NewServiceInfoForClient()
	twoServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return twoServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return twoServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return twoServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Two"
	handlerType := (*echo.Two)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "echo",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.1",
		Extra:           extra,
	}
	return svcInfo
}

func twoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(echo.Request)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(echo.Two).Two(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *TwoArgs:
		success, err := handler.(echo.Two).Two(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*TwoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newTwoArgs() interface{} {
	return &TwoArgs{}
}

func newTwoResult() interface{} {
	return &TwoResult{}
}

type TwoArgs struct {
	Req *echo.Request
}

func (p *TwoArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(echo.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *TwoArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *TwoArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *TwoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *TwoArgs) Unmarshal(in []byte) error {
	msg := new(echo.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var TwoArgs_Req_DEFAULT *echo.Request

func (p *TwoArgs) GetReq() *echo.Request {
	if !p.IsSetReq() {
		return TwoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *TwoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TwoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TwoResult struct {
	Success *echo.Response
}

var TwoResult_Success_DEFAULT *echo.Response

func (p *TwoResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(echo.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *TwoResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *TwoResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *TwoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *TwoResult) Unmarshal(in []byte) error {
	msg := new(echo.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *TwoResult) GetSuccess() *echo.Response {
	if !p.IsSetSuccess() {
		return TwoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TwoResult) SetSuccess(x interface{}) {
	p.Success = x.(*echo.Response)
}

func (p *TwoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TwoResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Two(ctx context.Context, Req *echo.Request) (r *echo.Response, err error) {
	var _args TwoArgs
	_args.Req = Req
	var _result TwoResult
	if err = p.c.Call(ctx, "Two", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
