// Code generated by Kitex v0.10.1. DO NOT EDIT.

package one

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	echo "multiple/kitex_gen/echo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"One": kitex.NewMethodInfo(
		oneHandler,
		newOneArgs,
		newOneResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	oneServiceInfo                = NewServiceInfo()
	oneServiceInfoForClient       = NewServiceInfoForClient()
	oneServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return oneServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return oneServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return oneServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "One"
	handlerType := (*echo.One)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "echo",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.1",
		Extra:           extra,
	}
	return svcInfo
}

func oneHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(echo.Request)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(echo.One).One(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *OneArgs:
		success, err := handler.(echo.One).One(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*OneResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newOneArgs() interface{} {
	return &OneArgs{}
}

func newOneResult() interface{} {
	return &OneResult{}
}

type OneArgs struct {
	Req *echo.Request
}

func (p *OneArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(echo.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *OneArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *OneArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *OneArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *OneArgs) Unmarshal(in []byte) error {
	msg := new(echo.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var OneArgs_Req_DEFAULT *echo.Request

func (p *OneArgs) GetReq() *echo.Request {
	if !p.IsSetReq() {
		return OneArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *OneArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OneArgs) GetFirstArgument() interface{} {
	return p.Req
}

type OneResult struct {
	Success *echo.Response
}

var OneResult_Success_DEFAULT *echo.Response

func (p *OneResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(echo.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *OneResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *OneResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *OneResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *OneResult) Unmarshal(in []byte) error {
	msg := new(echo.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *OneResult) GetSuccess() *echo.Response {
	if !p.IsSetSuccess() {
		return OneResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OneResult) SetSuccess(x interface{}) {
	p.Success = x.(*echo.Response)
}

func (p *OneResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OneResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) One(ctx context.Context, Req *echo.Request) (r *echo.Response, err error) {
	var _args OneArgs
	_args.Req = Req
	var _result OneResult
	if err = p.c.Call(ctx, "One", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
